#!/usr/bin/env python3

import glob
import subprocess
import sys

duration = 0
for f in glob.glob(sys.argv[1] + "/*.m4b"):
    try:
        output = subprocess.check_output(["ffmpeg", "-i", f], stderr=subprocess.STDOUT)
    except Exception as e:
        output = e.output.decode('utf-8')
    output = output.split('\n')
    for line in output:
        if 'Duration' in line:
            d = line[12:23]
            h, m, s, ms = int(d[0:2]), int(d[3:5]), int(d[6:8]), int(d[9:11]) * 10,
            duration += h * 60 * 60 + m * 60 + s
s = duration % 60
m = (duration / 60) % 60
h = (duration / 60 / 60)
print("{:02d}:{:02d}:{:02d}".format(int(h), int(m), int(s)))
