#!/bin/sh -x

# Remove stopped containers
docker ps --quiet --filter="status=exited" | xargs -n 1 docker rm
# Remove intermediate dangling images
docker images --quiet --filter="dangling=true" | xargs -n 1 docker rmi
# Remove intermediate dangling volumes
[ "$1" == "-v" ] && \
    docker volume ls --quiet --filter="dangling=true" | xargs -n 1 docker volume rm
