#!/bin/sh

sed ''/RUN/s//$(printf "\033[30;1mRUN\033[0m")/'' | \
sed ''/PASS:/s//$(printf "\033[32mPASS\033[0m:")/'' | \
sed ''/PASS/s//$(printf "\033[32;1mPASS\033[0m")/'' | \
sed ''/SKIP:/s//$(printf "\033[33mSKIP\033[0m:")/'' | \
sed ''/SKIP/s//$(printf "\033[33;1mSKIP\033[0m")/'' | \
sed ''/FAIL:/s//$(printf "\033[31mFAIL\033[0m:")/'' | \
sed ''/FAIL/s//$(printf "\033[31;1mFAIL\033[0m")/''
