#!/usr/bin/env python3

import csv
import sys


def main(args):
    if not args:
        return 'Usage: goodreads-export FILE'
    
    with open(args[0]) as fp:
        for row in csv.DictReader(fp):
            if not row['Date Read']:
                continue
            print('{} {:13} {} - {}'.format(row['Date Read'].replace('/', '-'), row['ISBN13'].strip('="'), row['Title'], row['Author']))

if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        sys.exit(1)
