#!/bin/bash

# Lookup wrapper around secret-tool for OSX.

if [[ $# -lt 3 ]]; then
  echo "Usage: secret-tool lookup [attribute] [value...]"
  exit 1
fi

SUBCOMMAND="$1"
SERVICE="$2"
ACCOUNT="$3"

if [[ "$SUBCOMMAND" != "lookup" ]]; then
  echo "Error: Only lookup subcommand supported"
  exit 1
fi

PASSWORD="$(security find-generic-password -w -s "$SERVICE" -a "$ACCOUNT" 2> /dev/null)"
RET_CODE=$?
case $RET_CODE in
   0) echo "$PASSWORD"; exit 0;;
  44) exit 1;; # Entry not found, which is ok
   *) exit $RET_CODE;;
esac
