;;; David Rocamora's emacs color theme.
;;; Colors stolen from Puredyne 
;;; Based on a Tango theme created by danranx@gmail.com

(defun color-theme-drr ()
  "David Rocamora's Emacs color theme."
  (interactive)
  (color-theme-install
   '(color-theme-drr
     ((background-color . "#262626")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "#A6E22E"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#555753"))))
     (font-lock-builtin-face ((t (:foreground "#66D9EF"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#A6E22E"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-keyword-face ((t (:foreground "#66D9EF" :bold t))))
     (font-lock-string-face ((t (:foreground "#F92672" :italic t))))
     (font-lock-type-face ((t (:foreground "#A6E22E" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (font-lock-warning-face ((t (:bold t :foreground "#FD971F"))))
     (font-lock-function-name-face ((t (:foreground "#edd400" :bold t :italic t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#A6E22E"))))
     (isearch ((t (:background "#FD971F" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#A6E22E"))))
     (show-paren-mismatch-face ((t (:background "#F92672" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#66D9EF" :bold t))))
     (info-xref ((t (:foreground "#66D9EF"))))
     (info-xref-visited ((t (:foreground "#F92672"))))
     )))

(provide 'color-theme-drr)
